const Project    = require('./models/Project');
const Skill      = require('./models/Skill');
const SiteContent = require('./models/SiteContent');

const projects = [
  { id:'portfolio',          title:'My Portfolio',                    shortDescription:'Showcasing creative, high-impact projects highlighting skills, innovation, problem-solving, and professional growth.',           writeup:'My Portfolio is a comprehensive showcase of my skills and projects, designed to highlight my expertise in web development. Built with HTML5, CSS, JavaScript, and Express.js, this project emphasizes clean design, smooth animations, and responsive layouts.',                                                                                                                                                                   image:'/assets/pic/prj-pics/tobbi-port.png',     tags:['HTML5','CSS','JavaScript','Express.js'],                repoUrl:'https://github.com/Tobbi49ja/Tobbi-Portfolio.git',          liveDemoUrl:'https://tobbi-portfolio.onrender.com/', featured:true,  order:0 },
  { id:'Student-Portal',     title:'A Student Management System',     shortDescription:'A streamlined, adaptable web application for handling student profiles, courses, and administrative tasks.',                       writeup:'The Student Management System is a streamlined web application designed to efficiently manage student profiles, courses, and administrative tasks. Developed with HTML, CSS, JavaScript, Node.js, Express, and MongoDB.',                                                                                                                                                                                           image:'/assets/pic/prj-pics/studentPort.png',    tags:['HTML5 & CSS3','Express with Node.js','MongoDB'],        repoUrl:'https://github.com/Tobbi49ja/Student-Portal.git',           liveDemoUrl:'https://student-management-system-hqbn.onrender.com/', featured:true, order:1 },
  { id:'movie-hub',          title:'A Functional Movie Hub',          shortDescription:'An interactive movie platform for streaming free movies, currently under active development and improvement.',                     writeup:'The Functional Movie Hub is an ambitious project aimed at providing a seamless movie streaming experience. Built with React Native, Vite, Express, and Node.js.',                                                                                                                                                                                                                                          image:'/assets/pic/prj-pics/movie.png',          tags:['React Native & Vite','Express','Node.js'],              repoUrl:'https://github.com/Tobbi49ja/movieReact.git',               liveDemoUrl:'https://moviereact-zzye.onrender.com/',                featured:true, order:2 },
  { id:'cfl-app',            title:'CFL APP',                         shortDescription:'A simple JavaScript program that reads, writes, and deletes files using file system operations.',                                  writeup:'The CFL APP is a lightweight JavaScript-based tool designed for file system operations, allowing users to read, write, and delete files efficiently.',                                                                                                                                                                                                                                                      image:'/assets/pic/prj-pics/CFL.APP (2).PNG',   tags:['JavaScript'],                                           repoUrl:'https://github.com/Tobbi49ja/-fileEditor.git',              liveDemoUrl:'',                                                      featured:false, order:3 },
  { id:'personal-portfolio', title:'Personal-Portfolio',              shortDescription:'A personal portfolio website showcasing my skills, projects, and experiences in a visually appealing format.',                    writeup:'A dedicated website to showcase my skills, projects, and professional journey. Built with HTML5, CSS, and JavaScript, it features a modern design with smooth animations and responsive layouts.',                                                                                                                                                                                                         image:'/assets/pic/prj-pics/portfolio.PNG',      tags:['HTML5','CSS','JavaScript'],                             repoUrl:'https://github.com/Tobbi49ja/fixingPortfolio.git',          liveDemoUrl:'',                                                      featured:false, order:4 },
  { id:'calculator',         title:'A Simple Calculator',             shortDescription:'A simple yet comprehensive tool for performing basic mathematical calculations easily.',                                           writeup:'A web-based application designed to perform basic mathematical operations with a clean and intuitive interface.',                                                                                                                                                                                                                                                                                          image:'/assets/pic/prj-pics/calculator.PNG',     tags:['HTML5','CSS','JavaScript'],                             repoUrl:'https://github.com/Tobbi49ja/A-simple-calculator.git',      liveDemoUrl:'',                                                      featured:false, order:5 },
  { id:'logistic-webpage',   title:'A Logistic Webpage',              shortDescription:'A logistics platform enabling customers to seamlessly track shipments and monitor delivery status online.',                        writeup:'The Logistic Webpage is a robust platform designed to streamline shipment tracking for customers. Built with React Native, MongoDB, and Node.js.',                                                                                                                                                                                                                                                       image:'/assets/pic/prj-pics/logistic-comp.PNG',  tags:['React Native','MongoDB','Node.js'],                     repoUrl:'#',                                                         liveDemoUrl:'',                                                      featured:false, order:6 },
  { id:'blog-webpage',       title:'A Blog Webpage',                  shortDescription:'Collaborated on GO-TRUTH blog app: crafted engaging content and seamless dark-mode user experience.',                             writeup:'The GO-TRUTH Blog Webpage is a collaborative project designed to deliver engaging content with a seamless dark-mode feature. Built with Python, Django, and HTML5.',                                                                                                                                                                                                                                     image:'/assets/pic/prj-pics/Go-truth.png',       tags:['Python','Django','HTML5'],                              repoUrl:'https://github.com/Jamesuchechi/GO-TRUTH-MAIN.git',         liveDemoUrl:'',                                                      featured:false, order:7 },
  { id:'netflix-homepage',   title:'Netflix Homepage',                 shortDescription:'A Netflix homepage clone built with HTML and Express, featuring a dynamic interface and responsive design.',                      writeup:'Replicates the iconic Netflix interface with a dynamic and responsive design. Built with HTML5, CSS, JavaScript, and Express.js.',                                                                                                                                                                                                                                                                       image:'/assets/pic/prj-pics/Netfilx.PNG',        tags:['HTML5','CSS','JavaScript'],                             repoUrl:'https://github.com/Tobbi49ja/NETFLIX-CLONE.git',            liveDemoUrl:'',                                                      featured:false, order:8 },
  { id:'receipt-generator',  title:'Receipt Generator',               shortDescription:'A class project to develop a receipt generator for assessing coding comprehension.',                                              writeup:'A class project demonstrating coding proficiency — a tool for generating receipts built with HTML5, CSS, and JavaScript.',                                                                                                                                                                                                                                                                               image:'/assets/pic/prj-pics/receipt-generator.PNG', tags:['HTML5','CSS','JavaScript'],                          repoUrl:'https://github.com/Tobbi49ja/class-project.git',            liveDemoUrl:'',                                                      featured:false, order:9 },
  { id:'fan-page',           title:'A Fan-Page',                      shortDescription:'A stylish fan page website inspired by beloved icons, created to engage and celebrate fans.',                                     writeup:'A visually captivating website crafted to honor Juice WRLD. Developed using HTML, CSS, and JavaScript with dynamic functionality and immersive animations.',                                                                                                                                                                                                                                            image:'/assets/pic/prj-pics/fan-page.PNG',       tags:['HTML5','CSS','JavaScript'],                             repoUrl:'https://github.com/Tobbi49ja/Fan-Page.git',                 liveDemoUrl:'https://fan-page.onrender.com',                         featured:false, order:10 },
];

const skills = [
  { name:'HTML5 & CSS3',    percent:95, category:'Technical',    order:0 },
  { name:'JavaScript',      percent:90, category:'Technical',    order:1 },
  { name:'React & Vite',    percent:85, category:'Technical',    order:2 },
  { name:'Express / Node.js', percent:80, category:'Technical',  order:3 },
  { name:'Svelte',          percent:65, category:'Technical',    order:4 },
  { name:'VPS / Linux',     percent:70, category:'Technical',    order:5 },
  { name:'UI/UX Design',    percent:85, category:'Professional', order:0 },
  { name:'Communication',   percent:90, category:'Professional', order:1 },
  { name:'Problem Solving', percent:95, category:'Professional', order:2 },
  { name:'Teamwork',        percent:88, category:'Professional', order:3 },
];

const content = [
  { key:'hero.title',           value:"Hi, I'm Tobbi",                                         type:'text' },
  { key:'hero.subtitlePhrases', value:'Full-Stack Developer,UI/UX Designer,Creative Builder',   type:'text' },
  { key:'about.title',          value:'Who am I?',                                              type:'text' },
  { key:'about.paragraph1',     value:"I'm a passionate Full-Stack Developer and creative Designer with 8 months of hands-on experience crafting responsive, visually engaging, and user-focused digital products. I specialize in frontend and backend development using modern technologies like HTML5, CSS3, JavaScript, React, Vite, Node.js, and Express, while also excelling in UI/UX and graphic design with tools like Figma, Canva, and Corel Draw.", type:'text' },
  { key:'about.paragraph2',     value:"My approach blends technical precision with a keen sense of design, delivering projects that perform seamlessly and delight users with exceptional experiences.", type:'text' },
  { key:'about.paragraph3',     value:"Beyond the screen, I unwind and recharge through my love for gaming, watching movies, and hanging out with friends. Whether I'm exploring new digital worlds, catching the latest films, or enjoying a fun outing, I believe in balancing hard work with genuine enjoyment and creativity.", type:'text' },
  { key:'profile.picture',      value:'/assets/pic/profile/Profile.jpg',                        type:'image' },
  { key:'contact.email',        value:'tolusamuel040@gmail.com',                                type:'text' },
  { key:'contact.phone',        value:'+234 8120 3844 79',                                      type:'text' },
  { key:'contact.location',     value:'Bwari Abuja Nigeria',                                    type:'text' },
];

async function seed() {
  if (await Project.countDocuments() === 0) {
    await Project.insertMany(projects);
    console.log('✅ Projects seeded');
  }
  if (await Skill.countDocuments() === 0) {
    await Skill.insertMany(skills);
    console.log('✅ Skills seeded');
  }
  if (await SiteContent.countDocuments() === 0) {
    await SiteContent.insertMany(content);
    console.log('✅ Site content seeded');
  }
}

module.exports = seed;
